### ISSUE TITLE
Coreth depends on `go-ethereum` 1.9, which requires downgrading `solc` for Go ABI binding generation

### ISSUE THREAD

**Issue by mieubrisse** [ava-labs/coreth#146]
This means that any project which a) wants to generate Go ABI bindings for a Solidity contract and b) imports avalanchego must intentionally downgrade a) their `go-ethereum` to 1.9 (latest is 1.10) and b) their `solc` to 0.7 (latest is 0.8).

This is because the Go ABI bindings generated by `go-ethereum` 1.10 aren't backwards compatible with 1.9, and `go-ethereum` 1.9 generation isn't forward-compatible with `solc` 0.8 (only 0.7).

**Comment by aaronbuchwald** [comment]
Closing since coreth has been updated to use v1.10.x
