### ISSUE TITLE
re-support debug_standardTraceBlockToFile

### ISSUE THREAD

**Issue by saurik** [ava-labs/coreth#177]
After burning two days trying to figure out how to get trace data out of avalanchego without having to painfully implement everything I want to do inside of coreth using Go (see https://github.com/ava-labs/avalanchego/issues/984, where I finally won against the numerous arbitrary limits imposed on the GRPC ping-pong being played with my 3G JSON result), I'm realizing that, in a very real sense, the core underlying issue I'm running into here is that Avalanche removed support for debug_standardTraceBlockToFile--which the geth people explicitly introduced in order to solve this problem of allowing the state to be streamed to disk rather than re-architecting all of the JSON encoders to not buffer everything into RAM--in 439d17395eab51cb73429c0f6e7cf751f74f8644. I don't understand why this was removed instead of merely moved to something like internal-file-tracing-debug and I particularly don't understand why the code for it had to be entirely deleted instead of merely disconnected (maximizing differences between coreth and geth).

Regardless, I can confirm that the code for this method from geth, if placed back in eth/tracers/api.go and edited for some trivial geth/coreth differences (which are hopefully due to version skew and aren't egregious edits), works. (Note that I did remove the Overrides if-block, as I didn't want to figure out what was going on with the namespaces there.)

**Comment by aaronbuchwald** [comment]
Thanks for digging into this, feel free to open a PR.

**Comment by aaronbuchwald** [comment]
Thanks for raising this issue early on.

This was a good callout and we have reversed our approach and re-introduced the file tracer API in the latest release in this commit: https://github.com/ava-labs/coreth/commit/d619f9cc17c35d481626d0f06777399908595244.
