### ISSUE TITLE
Where exactly in the Avalanche codebase does the gRPC communication happen with EVM? 

### ISSUE THREAD

**Issue by githubgitlabuser** [ava-labs/coreth#178]
> The C-Chain runs in a separate process from the main AvalancheGo process and communicates with it over a local gRPC connection.

Where exactly in the [Avalanche codebase](https://github.com/ava-labs/avalanchego) does the gRPC communication happen between Avalanche and EVM?

**Comment by ceyonur** [comment]
This is the VM that can talk with plugins through gRPC:
https://github.com/ava-labs/avalanchego/tree/master/vms/rpcchainvm

and this is where plugins are registered:
https://github.com/ava-labs/avalanchego/blob/master/node/node.go#L686

**Comment by aaronbuchwald** [comment]
Calls are made across the grpc broker ex. https://github.com/ava-labs/avalanchego/blob/master/vms/rpcchainvm/vm_client.go#L439.
