### ISSUE TITLE
How Do I Interact with ERC20 Token Programmatically 

### ISSUE THREAD

**Issue by rukolahasser** [ava-labs/coreth#184]
I'd like to get token info based on the address just like what I do in the ethereum:
```
// NewIERC20 creates a new instance of IERC20, bound to a specific deployed contract.
func NewIERC20(address common.Address, backend bind.ContractBackend) (*IERC20, error) {
	contract, err := bindIERC20(address, backend, backend, backend)
	if err != nil {
		return nil, err
	}
	return &IERC20{IERC20Caller: IERC20Caller{contract: contract}, IERC20Transactor: IERC20Transactor{contract: contract}, IERC20Filterer: IERC20Filterer{contract: contract}}, nil
}
```
But the avalanche `ethclient` is not compatible with it and missing some methods such as `PendingCodeAt(ctx context.Context, account common.Address) ([]byte, error)` to be implemented.

**Comment by aaronbuchwald** [comment]
We removed `PendingCodeAt` due to the fact that there is no notion of a pending block on the C-Chain. You should be able to use the coreth abi package in order to accomplish the same thing: `https://github.com/ava-labs/coreth/tree/master/accounts/abi/bind`
