### ISSUE TITLE
Testing swap X chain to C chain not work always getting insufficient AVAX burned (0) to cover import tx fee (3016350)

### ISSUE THREAD

**Issue by huuhait** [ava-labs/coreth#185]
Hi i'm trying to make avax work in local but i dont know how to transfer from X chain to C Chain

![image](https://user-images.githubusercontent.com/40519768/153728350-0ea2a2b8-4ae7-429e-bde1-8ded1737a334.png)

Thanks for your help

**Comment by aaronbuchwald** [comment]
Import/export transactions are required to burn more inputs than they produce in outputs (for those assets denominated in AVAX). The difference between these two is the total amount burned and must cover the transaction fee. For more information you can refer to the atomic transaction fees in our documentation here: https://docs.avax.network/learn/platform-overview/transaction-fees/#atomic-transaction-fees.

**Comment by huuhait** [comment]
> Import/export transactions are required to burn more inputs than they produce in outputs (for those assets denominated in AVAX). The difference between these two is the total amount burned and must cover the transaction fee. For more information you can refer to the atomic transaction fees in our documentation here: https://docs.avax.network/learn/platform-overview/transaction-fees/#atomic-transaction-fees.

Yes i read the source code but i really don't know how to burn avax from block 0 to create export/import transactions

**Comment by aaronbuchwald** [comment]
What do you mean by burn it from block 0? As mentioned, the difference between the inputs and outputs is the amount burned by the transaction, which covers the fee.
