### ISSUE TITLE
upgrading geth to support Istanbul

### ISSUE THREAD

**Issue by saurik** [ava-labs/coreth#19]
The Istanbul release of Ethereum from last December had a number of important changes, including a new opcode (chainid) that is used by our contracts for layer 2 fork protection (though the net gas metering change is also really important for a lot of contracts now, and the adjustments to the various other costs make some use cases much more viable, including zkp and rollups). Is there any hope of getting geth upgraded to a newer version? (I am not a Go developer myself, but it looks like you might not have made any real extensive changes to geth, other than to systematically change the all of import paths to your GitHub organization?)

https://medium.com/mycrypto/ethereums-istanbul-fork-technical-explanation-48a3aef718b0

**Comment by collincusce** [comment]
Why not Tavum, by the way?

https://github.com/ethereum/go-ethereum/releases/tag/v1.9.21

**Comment by saurik** [comment]
That name is an unrelated concept. I guess I used the term "release", but I mean "hard fork". I only care that the Ethereum you are using is compatible with Istanbul (and so like, if you are compiling a contract with Solidity, that you can use features that require ```--evm-version istanbul```). I am not sure what version of geth you need to support Istanbul, but certainly the latest one would work.

(FWIW, in case this is at all interesting, I noticed that Ethermint is already on 1.9.21, which is easy for them as they just treat geth as a normal module whose version they can bump, rather than having their own fork of geth; I'm not even sure why Avalanche has a fork... maybe that was just to fix the one warning a while back and you could switch back to just referencing ethereum/go-ethereum?)

The thing I'm not sure of is whether you have to configure geth in some way to make it use Istanbul; like, normally, Ethereum chooses which hard fork it is on based on what block number you are on, so they can schedule consensus level changes (such as Istanbul) in the future and have time for people to install new clients (in the hope that they can get X% of the clients/miners to upgrade first).

**Comment by saurik** [comment]
(AFAIK, Istanbul is the most recent hard fork that "matters" to a project like Avalanche/Athereum, as Muir Glacier--which came less than a month after Istanbul and which I think is still the most recent version now nine months later--didn't change anything except the difficulty bomb, which is part of the proof of work layer you aren't using.)

**Comment by collincusce** [comment]
> That name is an unrelated concept. I guess I used the term "release", but I mean "hard fork".

For those coming in, I asked "why not Tavum" and then about 20 seconds later I deleted the comment because it's, as @saurik said, an unrelated concept. Brain did a thing for a second. 

This information is good to have in this thread, @saurik , thank you for typing it out.

**Comment by Determinant** [comment]
@saurik It is part of our plan to dump up the version of geth used by coreth. But I'd say it is still too early to do it right now. We first need a working and robust C-Chain before changing our Ethereum implementation code base, upon which various hacks are applied. So it makes more sense for now to stick to one decent version until then.

**Comment by saurik** [comment]
While I find that a bit confusing, as I was 1) under the impression that you were intending to launch the C chain to production in the next couple weeks (and so I'd have hoped it would be working and robust ;P), and 2) I'd have expected that shipping a year-old codebase would itself cause a number of bugs... upgrading the version of geth is actually a bit orthogonal.

The version of geth you are using--0.9.3--in fact has support for Istanbul: you just haven't turned it on. That wasn't the release of geth everyone was using with Istanbul, because it doesn't have the correct hardcoded block number changes, but looking through all of the changelog entries for later releases I'm seeing no actual changes to the Istanbul functionality itself.

@Determinant So, then without upgrading to a later version of geth than 0.9.3, can you just turn on the Istanbul features? ;P

**Comment by saurik** [comment]
(Per some confusion I might have caused on Discord by talking in #athereum--which I did because the C-chain is reporting itself as using "Athereum 1.0" and because I didn't see any other channels that would have made sense--I might need to make it clear that I'm specifically interested in having this functionality on the C-chain: I have no interest in the Ethereum fork project, and am really hoping that Avalanche doesn't launch with an out-dated EVM on the C-chain.)

**Comment by saurik** [comment]
FWIW, working backwards a bit from the coreth plugin back into avalanchego, it seems like it might be that the only thing that has to be edited is the genesis/config.go in that project to choose a block at which to activate Istanbul (by setting istanbulBlock to a non-nil number; you already have petersburgBlock set to 0 so it was active from the start).

https://github.com/ava-labs/avalanchego/blob/1e70861181b4591f1631e5a2beb5dc30d6ae401b/genesis/config.go#L72

As those are encoded as hex I've included a decoded copy, expanding and indenting it a bit so the config block is more readable; the default value for istanbulBlock is nil/undefined, but it could be set here to say 400000 to allow for Istanbul to activate on the C-chain in a week or something like that (as I think I remember it being on 167000 last night).

```json
{"config":{
    "chainId":43110,
    "homesteadBlock":0,
    "daoForkBlock":0,
    "daoForkSupport":true,
    "eip150Block":0,
    "eip150Hash":"0x...",
    "eip155Block":0,
    "eip158Block":0,
    "byzantiumBlock":0,
    "constantinopleBlock":0,
    "petersburgBlock":0
},
"nonce":"0x0","timestamp":"0x0","extraData":"0x00",
"gasLimit":"0x5f5e100","difficulty":"0x0","mixHash":"0x...",
"coinbase":"0x...","alloc":{"...":{"code":"0x...","balance":"0x0"},"...":{
"balance":"0x..."}},"number":"0x0","gasUsed":"0x0","parentHash":"0x..."}
```

(I would actually argue that testing this flow before launch would also be good generally, btw, as if you ever want to upgrade the consensus in the future--such as to Berlin--you will need to make sure that having some random subset of validators on a slightly but not entirely different version of Ethereum isn't going to cause a serious problem.)

**Comment by saurik** [comment]
FWIW, I've now verified that this works by bootstrapping a local testnet with istanbulBlock at 0 (and I've also more carefully gone through even more sets of changelogs and issues to verify that geth 1.9.3 seems to have a complete implementation of Istanbul). So: no geth code upgrade required: this is just some configuration state that needs to be updated ;P.

The next step is how to coordinate this "hard fork", as this is a genesis configuration change. Again, the way this tends to work with Ethereum is that you schedule the change in the future, giving yourself enough time to get full nodes to upgrade; in the case of the Avalanche testnet, I'd imagine the main thing would just be to upgrade all of your own validators?

**Comment by Determinant** [comment]
@saurik we'll bump up the version before the mainnet. Thanks for the info. Working on it.

**Comment by Determinant** [comment]
Bumped the geth version to the latest as v0.3.0-rc.5. The Istanbul features should be available once we update the testnet genesis block.

**Comment by aaronbuchwald** [comment]
These features should be available on mainnet, fuji testnet, and the default local network. Thanks for catching this @saurik . Closing this issue since it's resolved.
