### ISSUE TITLE
where is the tx_fetcher.go and block_fetcher.go?

### ISSUE THREAD

**Issue by huahuayu** [ava-labs/coreth#191]
hi, I noticed that `eth/tx_fetcher.go` and `eth/block_fetcher.go` are removed from `coreth`, so where's are the hash -> transaction fetch logic now?

**Comment by aaronbuchwald** [comment]
These have been removed. Blocks are fetched and inserted by the Snowman consensus engine. The mempool transaction gossiping logic happens via App specific messages over the vm interface and is implemented in the `plugin/evm/` package.
