### ISSUE TITLE
`backends.SimulatedBackend` doesn't implement `ethclient.Client` interface

### ISSUE THREAD

**Issue by kare** [ava-labs/coreth#215]
`backends.SimulatedBackend` doesn't implement `ethclient.Client` interface

To Reproduce:
```
var _ ethclient.Client = (*backends.SimulatedBackend)(nil)
```

**Expected behavior**
No compiler error.

**Comment by kare** [comment]
Any comments? @aaronbuchwald @darioush @ceyonur

**Comment by aaronbuchwald** [comment]
Thanks for pointing this out, will fix this in the next release.

**Comment by aaronbuchwald** [comment]
There is no expectation for `backends.SimulatedBackend` to implement the same interface as `ethclient.Client` interface. These are both borrowed from go-ethereum where `ethclient.Client` is a struct and not an interface.

The struct `ethclient.Client` also does not match `backends.SimulatedBackend`.

**Comment by darioush** [comment]
Please feel free to open another issue describing what you were attempting to accomplish or if there is another concern, we appreciate the feedback.

**Comment by kare** [comment]
@darioush @aaronbuchwald Sorry about concise bug report. I'm new to Avalanche but I've used Ethereum before. With that I've unit tested my code by using `SimulatedBackend` and thought that it would apply here as well.

See [this article](https://medium.com/@m.vanderwijden1/intro-to-web3-go-part-4-5a21bc71fddc) for details on how to do unit testing with `SimulatedBackend` on Ethereum.

So my questions is should I just mock the client interface or does Avalanche provide some unit testing tools?

**Comment by ceyonur** [comment]
It applies, but AFAIK you don't need to use the client code to use simulatedBackend. As the article says it can replace the client itself without needing to use it's interface. If you can share your tests, we can help you further.
