### ISSUE TITLE
Section processing failed

### ISSUE THREAD

**Issue by kraikov** [ava-labs/coreth#23]
After broadcasting multiple “deploy” transactions, the chain got corrupted and the transactions were stuck in “Pending”. 
Resetting the node did not help.

Log message:

```ERROR[09-15|14:47:02.586] Section processing failed                type=bloombits error="chain reorged during section processing"```

**Comment by Determinant** [comment]
Is it related to https://github.com/ethereum/go-ethereum/issues/15169 ? We'll bump up the underlying version of geth and see whethere this gets fixed.

**Comment by kraikov** [comment]
Looks like the same problem, but I can't be sure. 

I don't know if it makes sense, but this happened on an address with ~140k transactions.
