### ISSUE TITLE
Blockscout DDoS network for rejected blocks (failed to fetch internal transactions for blocks | cannot access atomic state for block)

### ISSUE THREAD

**Issue by DSuvoZera** [ava-labs/coreth#252]
**Describe the bug**
We have deployed private test network based on Avalanche.
Use Blockscout as Explorer for it.
After making several transactions in network (transfers from wallet to wallet), Blockscout continuously in loop requests network for rejected blocks and shows error in terminal (pointed in **Logs** section). This error log has led us to **coreth**.

**To Reproduce**
Nothing extra. Doing several regular transactions.

**Expected behavior**
No DDoS.

**Logs**
`2023-05-09T14:04:36.831 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: ** (ErlangError) Erlang error: [%{code: -32000, data: %{block_number: 3, transaction_hash: "0xc38b00b403bfe564d5b929a99f07271a1d53e1448252cf03c2a01ce1cb584200", transaction_index: 0}, message: "processing block 1 failed: engine finalization check failed: cannot access atomic state for block 0xe7b0052f525771fd8aa9b7f20fbf6f6221d9b89d23e4e1c0f7e2d07b9c68d5f4"}]`

**Operating System**
Ubuntu

**Comment by aaronbuchwald** [comment]
Hey @DSuvoZera could you describe what API calls the external application is making that result in unexpected behavior?

**Comment by DSuvoZera** [comment]
The problem occurred on our side. Already fixed it. Thnx)
