### ISSUE TITLE
EADDRINUSE

### ISSUE THREAD

**Issue by AndonMitev** [ava-labs/coreth#26]
Basically i was spamming the network with transactions and a few hundred of them were processed successfully but then suddenly that error start pop up and i had to restart the node. (edited) 
It's a random error, I'm having 2 more machines next to me running without any issues for couple hours already (edited)

`9/15/2020, 10:35:36 AM error:   Send transaction error : {"reason":"missing response","code":"SERVER_ERROR","requestBody":"{\"method\":\"eth_getTransactionReceipt\",\"params\":[\"0x7fcef903203585d6e3386539ab083724b1177acc7bd77366d5aa36b9770f5a87\"],\"id\":34151,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","serverError":{"errno":"EADDRINUSE","code":"EADDRINUSE","syscall":"connect","address":"127.0.0.1","port":9650},"url":"http://127.0.0.1:9650/ext/bc/C/rpc"}`

**Comment by Determinant** [comment]
Could it be possible that you didn't kill the previous process (which already used the HTTP port/socket) before starting a new one? To check, could you reboot your machine and then do the test again to see whether the random error still appears?

**Comment by AndonMitev** [comment]
Well now I don't face it anymore but, before that error occur i manage to send like ~400 transactions successfully and after that few transactions later error shows up. I guess if i wasn't kill previous process i won't be able to broadcast any transactions

**Comment by AndonMitev** [comment]
Additionally node was fresh, i restart it before send these ~400 transactions successfully and then the failure come up

**Comment by Determinant** [comment]
Thanks for the update. Let me know if it reappears and feel free to reopen this issue.
