### ISSUE TITLE
Flaky test: TestTransactionIndices

### ISSUE THREAD

**Issue by darioush** [ava-labs/coreth#262]
--- FAIL: TestTransactionIndices (1.05s)
    blockchain_test.go:652: 
        	Error Trace:	/home/runner/work/coreth-internal/coreth-internal/core/blockchain_test.go:652
        	            				/home/runner/work/coreth-internal/coreth-internal/core/blockchain_test.go:731
        	Error:      	Not equal: 
        	            	expected: (*uint64)(0xc0085ead88)
        	            	actual  : (*uint64)(0xc000c49b58)
        	Test:       	TestTransactionIndices

observed to fail CI on unrelated PR

**Comment by ceyonur** [comment]
I think we have fixed this with recent updates to indexers.
