### ISSUE TITLE
Unable to run a node for XANAChain subnet

### ISSUE THREAD

**Issue by SalmanNoborderz** [ava-labs/coreth#281]
**Describe the bug**
Getting "Block failed verification during bootstrapping"

**To Reproduce**
Followed steps as mentioned in (https://docs.avax.network/nodes/build/run-avalanche-node-manually) and added --track-subnets=ii7zCu8JNnYYgPT8PwpVYiTS1gcK5RWJfsyuPXTDv8Bn9wspY

**Expected behavior**
It should be fully boostrapped with the the whitelisted subnet

**Logs**
[log.zip](https://github.com/ava-labs/coreth/files/12025110/log.zip)

**Operating System**
Ubuntu 18.04

**Comment by aaronbuchwald** [comment]
Hey @SalmanNoborderz , this looks like it corresponds to Subnet-EVM as opposed to coreth. Could you move the issue there? https://github.com/ava-labs/subnet-evm/issues.

Could you also provide the version of Subnet-EVM and AvalancheGo that you are running when you run into this issue?

**Comment by gyuho** [comment]
@SalmanNoborderz Also, please feel free to paste the corresponding logs in the github issue itself, rather than uploading the zip file.
