### ISSUE TITLE
Couldn't build abigen binary

### ISSUE THREAD

**Issue by christiankakesa** [ava-labs/coreth#355]
**Describe the bug**
When building `cmd/abigen/main.go`, 2 errors occurs: `undefined: nameFilter` and `undefined: newNamefilter`.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
No error and `abigen` binary created.

**Screenshots**

    christian@MSI:~/workspace/ava-labs-coreth/cmd/abigen$ go mod tidy
    christian@MSI:~/workspace/ava-labs-coreth/cmd/abigen$ go build -o abigen-avax main.go
    # command-line-arguments
    ./main.go:162:16: undefined: nameFilter
    ./main.go:165:22: undefined: newNameFilter

**Operating System**
GNU/linux Ubuntu 20.04.

Avalanche Bug Bounty program can be found [here](https://hackenproof.com/avalanche/avalanche-protocol).

**Comment by ceyonur** [comment]
It should be built from the root directory (where the `go.mod` file resides):
`christian@MSI:~/workspace/ava-labs-coreth$ go build -o ./abigen-avax cmd/abigen/*.go`

**Comment by christiankakesa** [comment]
Yes of course but many documentation mention only the way to do that by compiling directly main.go.
Take a look at this outdated documention: https://docs.avax.network/build/dapp/smart-contracts/abigen.

By the way it's OK for me.

**Comment by ceyonur** [comment]
Opened PR https://github.com/ava-labs/avalanche-docs/pull/1549/
Thanks for reporting this @christiankakesa.
