### ISSUE TITLE
gas tip cap < pool gas tip cap, and issue setting tx-pool-price-limit flag 

### ISSUE THREAD

**Issue by KyleMoser** [ava-labs/coreth#382]
**Environment**
Local docker network built off of Avalanche v1.10.1 using CIDT's [heighliner repo ](https://github.com/ConsiderItDone/heighliner/tree/avalanche_start_time) and the command `heighliner build --chain avalanche --git-ref v1.10.1`

**Problem**
When I send my TX to the C-Chain it says "github.com/ava-labs/coreth/rpc/handler.go:403: Served eth_sendRawTransaction conn=172.18.0.1:47790 reqid=8 execTime="874.354µs" procTime="881.966µs" totalTime="889.16µs" err="transaction underpriced: address 0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC have **gas tip cap (225000000000) < pool gas tip cap (470000000000)**".

**Workaround**
I can workaround this error by setting this in my TX:
```
bi, _ := new(big.Int).SetString("470000000000", 10)
auth.GasPrice = bi
```
With the above, my TX succeeds with a "1" Receipt status.

**Attempted solution**
This error message led me to search the avalanchego (and coreth) source code, and determine that I need to set a lower limit for _tx-pool-price-limit_. However, I have no idea where it gets "470000000000" from, as I cannot find anywhere that number is set. 

To set the tx-pool-price-limit, I set --chain-config-content eyJDIjp7IkNvbmZpZyI6ImV3b0pDU0pqYjI1bWFXY2lPaUI3Q2drSklDQWlkSGd0Y0c5dmJDMXdjbWxqWlMxc2FXMXBkQ0k2SURFS0NRbDlDZ2tnSUgwPSIsIlVwZ3JhZGUiOm51bGx9fQ== on startup (with the code below) but I cannot tell if it is doing anything - it certainly doesn't solve the problem (transaction underpriced error message above does not change).

**My code** 
(note that I'm using a local docker network w/ 5 nodes all launched similarly w/ this command):

```
injectedNodeTxConfig := `{
		"config": {
		  "tx-pool-price-limit": 1
		}
	  }`

	// See Avalanche documentation on --chain-config-content flag, as well as avalanchego source code for usage.
	// This overrides C chain's config params for tx-pool-price-limit.
	m := map[string]chains.ChainConfig{}
	m["C"] = chains.ChainConfig{Config: []byte(injectedNodeTxConfig)}
	jsonMaps, err := json.Marshal(m)
	if err != nil {
		return err
	}
	encodedFileContent := base64.StdEncoding.EncodeToString(jsonMaps)

	cmd := []string{
		n.chain.cfg.Bin,
		"--http-host", "0.0.0.0",
		"--data-dir", n.HomeDir(),
		"--public-ip", n.options.PublicIP,
		"--network-id", n.options.ChainID.String(),
		"--chain-config-content", encodedFileContent,
		"--genesis", filepath.Join(n.HomeDir(), "genesis.json"),
		"--staking-tls-cert-file", filepath.Join(n.HomeDir(), "tls.cert"),
		"--staking-tls-key-file", filepath.Join(n.HomeDir(), "tls.key"),
	}
```

**Comment by ceyonur** [comment]
470 navax It is the launch price https://github.com/ava-labs/coreth/blob/dynamic-bloom/params/avalanche_params.go#L16. After that it should decrease to 25 navax (since after the first block your chain will be upgraded to AP5). Note that Coreth uses dynamic fees so you should use estimate fee APIs. More info available [here](https://docs.avax.network/build/dapp/advanced/sending-transactions-with-dynamic-fees-using-javascript#setting-up-c-chain-apis-for-estimating-base-and-priority-fees).

**Comment by ceyonur** [comment]
Closing the stale issue. Feel free to reopen. 

Thanks.
