### ISSUE TITLE
 Error when running local coreth

### ISSUE THREAD

**Issue by AndyCYB** [ava-labs/coreth#480]
1. I want to build an avax node on the server. I downloaded the avalanchego code according to the instructions and the node can run normally.

2. I want my node to run local coreth code. I cloned the coreth code to the same directory as avalanchego, and then ran it according to the instructions:  go mod edit -replace github.com/ava-labs/coreth=../coreth
command, then run:  ./scripts/build.sh
An error was reported, and the error message was as follows:

Downloading dependencies...
Building AvalancheGo...
# github.com/ava-labs/coreth/internal/debug
../coreth/internal/debug/flags.go:190:22: undefined: log.Handler
../coreth/internal/debug/flags.go:194:35: undefined: log.StreamHandler
../coreth/internal/debug/flags.go:194:64: undefined: log.TerminalFormat
../coreth/internal/debug/flags.go:196:13: log.Root().SetHandler undefined (type "github.com/ethereum/go-ethereum/log".Logger has no field or method SetHandler)
../coreth/internal/debug/flags.go:203:18: undefined: log.Format
../coreth/internal/debug/flags.go:211:16: undefined: log.JSONFormat
../coreth/internal/debug/flags.go:213:16: undefined: log.JSONFormat
../coreth/internal/debug/flags.go:215:16: undefined: log.LogfmtFormat
../coreth/internal/debug/api.go:69:24: undefined: log.Lvl
../coreth/internal/debug/api.go:81:17: glogger.BacktraceAt undefined (type *"github.com/ethereum/go-ethereum/log".GlogHandler has no field or method BacktraceAt)
../coreth/internal/debug/flags.go:215:16: too many errors
# github.com/ava-labs/avalanchego/database/pebble
database/pebble/db.go:94:32: cannot use cfg.MemTableSize (variable of type int) as uint64 value in struct literal
database/pebble/db.go:209:9: assignment mismatch: 1 variable but db.pebbleDB.NewIter returns 2 values
database/pebble/db.go:256:9: multiple-value db.pebbleDB.NewIter(keyRange(start, prefix)) (value of type (*"github.com/cockroachdb/pebble".Iterator, error)) in single-value context
# github.com/ava-labs/coreth/core/rawdb
../coreth/core/rawdb/database.go:130:9: cannot use &nofreezedb{…} (value of type *nofreezedb) as ethdb.Database value in return statement: *nofreezedb does not implement ethdb.Database (wrong type for method TruncateHead)
		have TruncateHead(uint64) error
		want TruncateHead(uint64) (uint64, error)
../coreth/core/rawdb/databases_64bit.go:32:57: not enough arguments in call to pebble.New
	have (string, int, int, string, bool)
	want (string, int, int, string, bool, bool)
../coreth/core/rawdb/table.go:42:9: cannot use &table{…} (value of type *table) as ethdb.Database value in return statement: *table does not implement ethdb.Database (wrong type for method TruncateHead)
		have TruncateHead(uint64) error
		want TruncateHead(uint64) (uint64, error)
../coreth/core/rawdb/table.go:111:9: too many return values
	have (uint64, error)
	want (error)
../coreth/core/rawdb/table.go:117:9: too many return values
	have (uint64, error)
	want (error)

I haven’t changed any code in coreth. Why am I getting an error?

**Comment by AndyCYB** [comment]
I re-executed it according to your command and it can indeed be compiled. But now I want to transplant my eth code to coreth. May I ask which version code of go-ethereum fork coreth is? I can easily transplant the corresponding version of the code.

**Comment by AndyCYB** [comment]
I used the 1.10.26 version of the go-ethereum code to transplant it to coreeth, but the following related errors were reported. Should I use this version of the code：

Downloading dependencies...
Building AvalancheGo...
# github.com/ava-labs/coreth/internal/ethapi
../coreth/internal/ethapi/api.go:2324:30: s.b.ChainConfig().IsLondon undefined (type *"github.com/ava-labs/coreth/params".ChainConfig has no field or method IsLondon)
../coreth/internal/ethapi/api.go:2325:30: cannot use s.b.ChainConfig() (value of type *"github.com/ava-labs/coreth/params".ChainConfig) as *"github.com/ethereum/go-ethereum/params".ChainConfig value in argument to misc.CalcBaseFee
../coreth/internal/ethapi/api.go:2325:49: cannot use parent (variable of type *"github.com/ava-labs/coreth/core/types".Header) as *"github.com/ethereum/go-ethereum/core/types".Header value in argument to misc.CalcBaseFee
../coreth/internal/ethapi/api.go:2359:48: not enough arguments in call to types.MakeSigner
	have (*"github.com/ava-labs/coreth/params".ChainConfig, *big.Int)
	want (*"github.com/ava-labs/coreth/params".ChainConfig, *big.Int, uint64)
../coreth/internal/ethapi/api.go:2368:27: assignment mismatch: 3 variables but core.ApplyTransaction returns 2 values
../coreth/internal/ethapi/api.go:2368:77: cannot use &coinbase (value of type *"github.com/ethereum/go-ethereum/common".Address) as vm.BlockContext value in argument to core.ApplyTransaction

**Comment by darioush** [comment]
Not sure what you are trying to accomplish, could you provide more context?

Each version of coreth is only compatible with the go-ethereum version that is specified in its go.mod, for example master is now compatible with v1.12.0 (https://github.com/ava-labs/coreth/blob/master/go.mod#L12)

**Comment by AndyCYB** [comment]
Thank you for the information. I will develop it based on your information first. Thanks again.
