### ISSUE TITLE
 The  Self-built local node has a 1-2s delay compared to the public node

### ISSUE THREAD

**Issue by AndyCYB** [ava-labs/coreth#490]
Hello, I used a linux server(Server details at the end) to set up avalanche node according to the documentation:
https://gist.github.com/0fuz/8993a38019cb54e72dbdf44e2bed6734#file-avax_state_sync_node-md

At present, the node has been synchronized and the blocknumber can be obtained. But by comparing it with the public node: https://avalanche-c-chain.publicnode.com
I found that my local node is 1-2s slower than the public node, which is almost a block. 
![image](https://github.com/ava-labs/coreth/assets/13011168/2f60a8f6-a1a0-445c-b57e-909f90b9809a)

Is there any way to synchronize the local node I built to the latest block? My work needs to use the latest node data. Slow blocks have a serious impact on me. Thank you. 

My server information is as follows:
CPU
16 cores / 32 threads @ 4 GHz
Generation:
Raphael (Zen 4)
RAM
128 GB DDR5 ECC
Drives
min. 2 x 1.92 TB NVMe SSD Datacenter Edition (Gen4)

Up to 6 x optional (at additional cost)

NVMe, SATA and HDD available

**Comment by darioush** [comment]
Validators can receive `Push/PullQuery`s, so they are going to learn about blocks faster than non-validators.
We don't know the infrastructure behind `publicnode`. It's also possible they modified the consensus parameters (decreasing beta and increasing the rate of polling for new block data could improve the latency).
