### ISSUE TITLE
Broken Link to Setup API Namespaces in README

### ISSUE THREAD

**Issue by akaladarshi** [ava-labs/coreth#493]
I've encountered a broken link in the README.md file that's supposed to lead to instructions for setting up API namespaces in C-Chain. The links, which are found under the API section, does not lead to the intended destination.

Broken Link: [Setup API Namespaces](https://github.com/ava-labs/coreth/blob/master/README.md#api).

**Comment by ceyonur** [comment]
Thanks for opening the issue. I fixed them in https://github.com/ava-labs/coreth/pull/494
