### ISSUE TITLE
Atomic transactions on C-Chain

### ISSUE THREAD

**Issue by ageorgief** [ava-labs/coreth#522]
Hi!
How can I extract the transactionHash of an atomic transaction from the extra data of the block where in the readme is said that the atomic transactions are contained?

**Comment by darioush** [comment]
The recommended way to parse the extra data bytes is as such:
https://github.com/ava-labs/coreth/blob/0a3ee0ac03a303931193a21c28a86998da454467/plugin/evm/vm.go#L993

in other words, the extra bytes are either a single or slice of [this struct](https://github.com/ava-labs/coreth/blob/0a3ee0ac03a303931193a21c28a86998da454467/plugin/evm/tx.go#L137) depending on whether the block is before or after the Apricot Phase 5 upgrade, as encoded by the avalanchego codec.

You can call `tx.ID()` to get the hash (ID) of the atomic transaction.

**Comment by ageorgief** [comment]
I tried this but still cannot extract the transaction Hash. Let dive deep:

**Comment by darioush** [comment]
I seem to get the correct value, please check this UT https://github.com/ava-labs/coreth/compare/repro-522 
Perhaps the conversion to base58 is not handled differently than https://pkg.go.dev/github.com/ava-labs/avalanchego@v1.11.3/utils/cb58.
