### ISSUE TITLE
Improve security by updating blst to version 0.3.12

### ISSUE THREAD

**Issue by vtamara** [ava-labs/coreth#614]
**Is your feature request related to a problem? Please describe.**
blst 0.3.11 produces segmentation faults in OpenBSD due to constants present in a text section instead of being in a read-only section.  The problem was solved in version 0.3.12. See https://github.com/supranational/blst/issues/206

**Describe the solution you'd like**
Update of blst 

**Describe alternatives you've considered**

**Additional context**
Please see https://github.com/ava-labs/avalanchego/issues/3079

**Comment by darioush** [comment]
Closing as the dependency is now updated
