### ISSUE TITLE
eth_baseFee returns null on `v1.11.11`

### ISSUE THREAD

**Issue by exp0nge** [ava-labs/coreth#660]
**Describe the bug**
When calling `eth_baseFee`, it returns null on the latest release

```
{
  "jsonrpc" : "2.0",
  "method" : "eth_baseFee",
  "params" : [ ],
  "id" : 0
}
```

```
{
  "jsonrpc" : "2.0",
  "id" : 0,
  "result" : null
}
```

**To Reproduce**
We are running a local network version:

```
--config-file=/build/dev/config/config.json --chain-config-dir=/build/dev/config --sybil-protection-enabled=false" --network-id=local
```

config.json:

```
{
    "pruning-enabled": false,
    "http-host": "0.0.0.0",
    "staking-enabled": false,
    "bootstrap-ips": [],
    "bootstrap-ids": [],
    "snow-sample-size": 1,
    "snow-quorum-size": 1,
    "snow-mixed-query-num-push-vdr": 1
}
```

C/config.json
```
{
  "gasLimit": 15000000,
  "pruning-enabled": false, 
  "offline-pruning-enabled": false,
  "eth-apis": [
      "public-eth",
      "public-eth-filter",
      "net",
      "web3",
      "internal-public-eth",
      "internal-public-blockchain",
      "internal-public-transaction-pool",
      "internal-public-account",
      "debug-tracer",
      "internal-public-debug",
      "internal-private-debug"
    ]
}
```

We pull the linux-amd64 image into a debian base image.

**Expected behavior**
The current base fee is returned

**Screenshots**

**Logs**
If applicable, please include the relevant logs that indicate a problem and/or the log directory of your node. By default, this can be found at `~/.avalanchego/logs/`.

**Metrics**
If applicable, please include any metrics gathered from your node to assist us in diagnosing the problem.

**Operating System**
Debian

**Additional context**

Avalanche Bug Bounty program can be found [here](https://hackenproof.com/avalanche/avalanche-protocol).

**Comment by michaelkaplan13** [comment]
Thanks for reporting this.

Are you running an AvalancheGo binary directly, or using the Avalanche CLI?

Could you also provide the full request information including the URL?

When I run a local network using the Avalanche CLI and AvalancheGo v1.11.11, I do not see this behavior:
```
$ avalanche network start
Backend controller started, pid: 6011, output at: /.../.avalanche-cli/runs/server_20240924_102837/avalanche-cli-backend.log
Installing avalanchego-v1.11.11...
avalanchego-v1.11.11 installation successful
A new network snapshot image is available. Replacing the current one.
Starting previously deployed and stopped snapshot
Booting Network. Wait until healthy...
Node logs directory: /.../.avalanche-cli/runs/network_20240924_102839/node<i>/logs

Network ready to use.

+--------------------------------------------------------------------------+
|                                   NODES                                  |
+-------+------------------------------------------+-----------------------+
| NAME  | NODE ID                                  | LOCALHOST ENDPOINT    |
+-------+------------------------------------------+-----------------------+
| node1 | NodeID-7Xhw2mDxuDS44j42TCB6U5579esbSt3Lg | http://127.0.0.1:9650 |
+-------+------------------------------------------+-----------------------+
| node2 | NodeID-MFrZFVCXPv5iCn6M9K6XduxGTYp891xXZ | http://127.0.0.1:9652 |
+-------+------------------------------------------+-----------------------+
| node3 | NodeID-NFBbbJ4qCmNaCzeW7sxErhvWqvEQMnYcN | http://127.0.0.1:9654 |
+-------+------------------------------------------+-----------------------+
| node4 | NodeID-GWPcbFJZFfZreETSoWjPimr846mXEKCtu | http://127.0.0.1:9656 |
+-------+------------------------------------------+-----------------------+
| node5 | NodeID-P7oB2McjBGgW2NXXWVYjV8JEDFoW9xDE5 | http://127.0.0.1:9658 |
+-------+------------------------------------------+-----------------------+



$ curl --location 'http://127.0.0.1:9650/ext/bc/C/rpc' \
> --header 'Content-Type: application/json' \
> --data '{
>     "jsonrpc": "2.0",
>     "method": "eth_baseFee",
>     "params": [],
>     "id": 67
> }'
{"jsonrpc":"2.0","id":67,"result":"0x34630b8a00"}

**Comment by exp0nge** [comment]
@michaelkaplan13 We're using the binary directly.

Here's the curl:
```
$ curl http://localhost:9650/ext/bc/C/rpc -X POST -H "Content-Type: application/json" --data '{"jsonrpc" : "2.0","id" : 0,"method" : "eth_baseFee","params" : [ ]}'
{"jsonrpc":"2.0","id":0,"result":null}
```

Attached are the docker logs:
[avax-11-log.txt](https://github.com/user-attachments/files/17116337/avax-11-log.txt)

Based on your comment, it looks like CLI might be doing an extra setup to get this working

**Comment by exp0nge** [comment]
Another difference I think is CLI creates a non-standard `local` network ID based on the fact that it generates a new genesis file

**Comment by michaelkaplan13** [comment]
Looks like the issue was just the timestamp of the default genesis block in AvalancheGo. Created a PR to fix it here
https://github.com/ava-labs/avalanchego/pull/3413

Thanks again for calling this out.

**Comment by michaelkaplan13** [comment]
> > Looks like the issue was just the timestamp of the default genesis block in AvalancheGo. Created a PR to fix it here [ava-labs/avalanchego#3413](https://github.com/ava-labs/avalanchego/pull/3413)
> > Thanks again for calling this out.
> 
> Thanks! Do you have rough estimate of when this will make into a release? Debating if I should swap to building from source to patch this ourselves versus waiting for a release versus getting a custom genesis state going (like CLI).

There aren't currently any releases planned, so my best guess would be a couple weeks or so.

Alternatively, as a basic workaround, if you send a transaction on the local C-Chain it should be included in a block and advance the chain timestamp to the current time, which should solve the base fee API response issue.

**Comment by exp0nge** [comment]
> > > Looks like the issue was just the timestamp of the default genesis block in AvalancheGo. Created a PR to fix it here [ava-labs/avalanchego#3413](https://github.com/ava-labs/avalanchego/pull/3413)
> > > Thanks again for calling this out.
> > 
> > 
> > Thanks! Do you have rough estimate of when this will make into a release? Debating if I should swap to building from source to patch this ourselves versus waiting for a release versus getting a custom genesis state going (like CLI).
> 
> There aren't currently any releases planned, so my best guess would be a couple weeks or so.
> 
> Alternatively, as a basic workaround, if you send any transaction on the local C-Chain it should be included in a block and advance the chain timestamp to the current time, which should solve the base fee API response issue.

Will look into submitting a raw tx to advance.

I was looking at running a custom network since I thought that would be useful and I used the gensis_local.json (except for the network-id value). In that, I took a look at that file - I don't understand the correlation to the fix given this value was 0 for a long time in the history of this file. This leaves me unsure if this is the only broken diff in `local` network

**Comment by exp0nge** [comment]
@michaelkaplan13 I've tried to submit a signed tx to advance, but the tx does not get mined in:

Legacy tx:
```
curl localhost:9650/ext/bc/C/rpc -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params": ["0xf86780850826299e00825208948db97c7cece249c2b98bdc0226cc4c2a57bf52fc0180830150f4a0207fe80fc8061897b492b8dd2b11ddb848cce3183c8e68469fcfb52b5ca37020a01385efacda067e2b2051a48081325a3e086d4360d9d98b6e5cf36577be293f86"],"id":1}'
```
I see node logs:
```
[09-25|20:13:59.554] INFO <C Chain> internal/ethapi/api.go:1791 Submitted transaction                    hash=0xb49d8e7a0bafd52beb2a15824e5171c153d7cc7531eeb0ccec44c198ef8f6c56 from=0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC nonce=0 recipient=0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC value=1 type=0 gasFeeCap=35,000,000,000 gasTipCap=35,000,000,000 gasPrice=35,000,000,000
[09-25|20:13:59.554] INFO <C Chain> core/state_processor.go:237 Activating new precompile                name=warpConfig config="{\"blockTimestamp\":1607144400,\"quorumNumerator\":0}"
```

`eth_baseFee` also returns null as this does not get mined in. Was there a particular style to get this to get mined in?

**Comment by michaelkaplan13** [comment]
Glad that worked! 

I believe the change was a result of an update to how coreth sources the upgrade timestamps from AvalancheGo. Prior to that update, the upgrades activated at timestamp 0 also, but now they activate at the [InitiallyActiveTime](https://github.com/ava-labs/avalanchego/blob/master/upgrade/upgrade.go#L16), so the genesis timestamp had to be changed to not be before then.

If you're modifying the genesis file already for the network ID, it is also safe to make that same change to the C-Chain genesis timestamp too 👍

**Comment by exp0nge** [comment]
To summarize (and for posterity), the options available:

1. doing one tx before interacting with the chain will provide correct responses (above: https://github.com/ava-labs/coreth/issues/660#issuecomment-2375169409)
2. initializing a custom network with the updated value provided in the fix PR above will also serve to fix the same thing but at the "chain" level more directly (of course this is not needed once the release is cut with the fix). I'll leave the configs that worked for us here:

[dev-c-config.json](https://github.com/user-attachments/files/17138570/dev-c-config.json)
[dev-config.json](https://github.com/user-attachments/files/17138571/dev-config.json)
[genesis.json](https://github.com/user-attachments/files/17138572/genesis.json)

we invoke the bin via: 

```
avalanchego --network-id="network-1337" --config-file=/build/dev/config/config.json --chain-config-dir=/build/dev/config --sybil-protection-enabled=false --api-admin-enabled=true --index-enabled=true --network-max-reconnect-delay=1s --http-host 0.0.0.0
```
